# Conclusion

In this project, Yudong Zhou and Yanbo Wang mainly focused on the export data of the United States from the 1970s and 1980s to the present, and completed multivariate analysis, time series analysis and data visualization. \
\
The main work includes three major parts: \
1. using professional databases to retrieve U.S. export data; \
2. processing data - such as data cleaning and data wrangling;\
3. rationally using what we have learned from the course to complete the visualization of multivariate analysis and time series analysis. \
\
Through this project, it is not difficult to see that with the development of time, the process of globalization has been substantially promoted. Although there are differences in scale, the export data of the United States to different regions and countries have shown an increasing trend. Combined with actual policies and practical results, we can conclude: promoting cooperation and development is the source of power for the common progress of the big family of all countries in the world. In the future development process, we must seek common ground while reserving differences, respect each other, cooperate for win-win results, and seek common progress.\
\
Eventually, we hope that this project can not only help students who are learning data visualization, but also remind everyone to let go of hostility, promote cooperation, and make progress together.